# Generated by Django 5.1.3 on 2025-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=6)),
                ('company_name', models.CharField(blank=True, max_length=20)),
                ('company_for', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled_buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.CharField(max_length=9)),
                ('Date', models.DateField()),
                ('F', models.CharField(max_length=20)),
                ('T', models.CharField(max_length=20)),
                ('Driver_name', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=10)),
            ],
        ),
    ]
