# Generated by Django 5.1.3 on 2025-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='company_for',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=65),
        ),
    ]
