# Generated by Django 5.1.3 on 2025-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0002_remove_registration_company_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.BinaryField(),
        ),
    ]
