# Generated by Django 5.1.3 on 2025-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0003_alter_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_buses',
            name='Type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
