# Generated by Django 5.1.3 on 2025-01-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0005_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
