# Generated by Django 5.1.3 on 2025-01-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0006_delete_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_buses',
            name='Type',
        ),
    ]
