# Generated by Django 5.1.3 on 2025-01-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0007_remove_scheduled_buses_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_buses',
            name='Price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.CharField(max_length=9)),
                ('Date', models.DateField()),
                ('U1', models.BooleanField(default=False)),
                ('U2', models.BooleanField(default=False)),
                ('U3', models.BooleanField(default=False)),
                ('U4', models.BooleanField(default=False)),
                ('U5', models.BooleanField(default=False)),
                ('U6', models.BooleanField(default=False)),
                ('U7', models.BooleanField(default=False)),
                ('U8', models.BooleanField(default=False)),
                ('U9', models.BooleanField(default=False)),
                ('U10', models.BooleanField(default=False)),
                ('U11', models.BooleanField(default=False)),
                ('U12', models.BooleanField(default=False)),
                ('U13', models.BooleanField(default=False)),
                ('U14', models.BooleanField(default=False)),
                ('U15', models.BooleanField(default=False)),
                ('U16', models.BooleanField(default=False)),
                ('U17', models.BooleanField(default=False)),
                ('U18', models.BooleanField(default=False)),
                ('L1', models.BooleanField(default=False)),
                ('L2', models.BooleanField(default=False)),
                ('L3', models.BooleanField(default=False)),
                ('L4', models.BooleanField(default=False)),
                ('L5', models.BooleanField(default=False)),
                ('L6', models.BooleanField(default=False)),
                ('L7', models.BooleanField(default=False)),
                ('L8', models.BooleanField(default=False)),
                ('L9', models.BooleanField(default=False)),
                ('L10', models.BooleanField(default=False)),
                ('L11', models.BooleanField(default=False)),
                ('L12', models.BooleanField(default=False)),
                ('L13', models.BooleanField(default=False)),
                ('L14', models.BooleanField(default=False)),
                ('L15', models.BooleanField(default=False)),
                ('L16', models.BooleanField(default=False)),
                ('L17', models.BooleanField(default=False)),
                ('L18', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buskarro_app.scheduled_buses')),
            ],
        ),
    ]
