# Generated by Django 5.1.3 on 2025-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0008_scheduled_buses_price_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_buses',
            name='Price',
            field=models.IntegerField(blank=True),
        ),
    ]
