# Generated by Django 5.1.3 on 2025-01-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0010_alter_scheduled_buses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_buses',
            name='Price',
        ),
    ]
