# Generated by Django 5.1.3 on 2025-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0014_remove_bus_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_buses',
            name='Bus_No',
            field=models.CharField(max_length=11),
        ),
    ]
