# Generated by Django 5.1.3 on 2025-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0015_alter_scheduled_buses_bus_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_buses',
            name='Bus_No',
            field=models.CharField(max_length=15),
        ),
    ]
