# Generated by Django 5.1.3 on 2025-01-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0016_alter_scheduled_buses_bus_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='Bus_No',
            field=models.CharField(max_length=15),
        ),
    ]
