# Generated by Django 5.1.3 on 2025-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0018_scheduled_buses_no_of_seats_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_buses',
            name='F',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduled_buses',
            name='T',
            field=models.CharField(max_length=50),
        ),
    ]
