# Generated by Django 5.1.3 on 2025-01-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0020_bus_f_bus_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='F',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='T',
        ),
    ]
