# Generated by Django 5.1.3 on 2025-01-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buskarro_app', '0021_remove_bus_f_remove_bus_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='F',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='T',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
