from django.db import models

# Create your models here.

class Registration(models.Model):
    Username = models.CharField(max_length=50,blank=False,unique=True)
    Email = models.EmailField(blank=False,unique=True)
    Password = models.BinaryField(blank=False)
    auth = models.CharField(max_length=6,blank=False)

class Scheduled_buses(models.Model):
    Bus_No = models.CharField(max_length=15,blank=False)
    Date = models.DateField(blank=False)
    F = models.CharField(max_length=50,blank=False)
    T = models.CharField(max_length=50,blank=False)
    Driver_name = models.CharField(max_length=50,blank=False)
    Price = models.IntegerField(blank=False)
    Time = models.CharField(max_length=10,blank=False)
    Seats = models.IntegerField(default=36)
    No_of_seats_booked = models.IntegerField(default=0)

class Bus(models.Model):
    Bus_No = models.CharField(max_length=15,blank=False)
    Date = models.DateField(blank=False)
    F = models.CharField(max_length=50,blank=False)
    T = models.CharField(max_length=50,blank=False)
    U1 = models.BooleanField(default=False)
    U2 = models.BooleanField(default=False)
    U3 = models.BooleanField(default=False)
    U4 = models.BooleanField(default=False)
    U5 = models.BooleanField(default=False)
    U6 = models.BooleanField(default=False)
    U7 = models.BooleanField(default=False)
    U8 = models.BooleanField(default=False)
    U9 = models.BooleanField(default=False)
    U10 = models.BooleanField(default=False)
    U11 = models.BooleanField(default=False)
    U12 = models.BooleanField(default=False)
    U13 = models.BooleanField(default=False)
    U14 = models.BooleanField(default=False)
    U15 = models.BooleanField(default=False)
    U16 = models.BooleanField(default=False)
    U17 = models.BooleanField(default=False)
    U18 = models.BooleanField(default=False)
    L1 = models.BooleanField(default=False)
    L2 = models.BooleanField(default=False)
    L3 = models.BooleanField(default=False)
    L4 = models.BooleanField(default=False)
    L5 = models.BooleanField(default=False)
    L6 = models.BooleanField(default=False)
    L7 = models.BooleanField(default=False)
    L8 = models.BooleanField(default=False)
    L9 = models.BooleanField(default=False)
    L10 = models.BooleanField(default=False)
    L11 = models.BooleanField(default=False)
    L12 = models.BooleanField(default=False)
    L13 = models.BooleanField(default=False)
    L14 = models.BooleanField(default=False)
    L15 = models.BooleanField(default=False)
    L16 = models.BooleanField(default=False)
    L17 = models.BooleanField(default=False)
    L18 = models.BooleanField(default=False)

class Contact(models.Model):
    Email = models.EmailField(blank=False)
    Message = models.TextField(blank=False)
    Date = models.DateField()
    is_solved = models.BooleanField(default=False)

